### ISSUE TITLE
|**Error 14: Couldn't find any gene trees in your gene tree input file (-g)! |

### ISSUE THREAD

**Issue by sskspider** [gwct/grampa#5]
Hi Gregg,

I have installed Grampa and the test data set works fine. 
However, another test data set that I prepared seems to have some issue that I am unable to figure out. The error says, 
"|**Error 14: Couldn't find any gene trees in your gene tree input file (-g)! |"

Can you please take a look at my gene and species tree?

Thank you!

Best,
Siddharth
[tree-files.zip](https://github.com/gwct/grampa/files/8235786/tree-files.zip)
.

**Comment by gwct** [comment]
Hi Siddarth,
It looks like your trees contain polytomies. I notice that the circled node in the image below has three descending branches:

![image](https://user-images.githubusercontent.com/12522633/158000480-abe822fb-0366-4764-8dcb-8ef11a461f48.png)

Unfortunately, GRAMPA can't currently account for polytomies correctly (see #4). This information would have been printed in the filtered gene trees file, but if all your gene trees aren't read then the program exits before that file is written.

In this case, I'm wondering if the outgroup (1_ROOT) was simply added on to the unrooted tree string. Unfortunately that won't work here since this results in the polytomy. Of course outgroup rooting is difficult for gene trees that contain paralogs, but maybe [Notung's](https://www.cs.cmu.edu/~durand/Notung/) rooting mode could be helpful. It uses an algorithm similar to GRAMPA's to root the gene trees.

**Comment by sskspider** [comment]
Hi Gregg, thanks a ton for the reply. So, I recovered the rooted genetrees using Notung's rooting mode and then used Grampa.
Problem solved!

Best,
Siddharth.
